### PR TITLE
Add spawner again

### PR DESCRIPTION
**Pull request by LNJplus**
I've got a friend who builded a trap for sheeps, that kills the sheeps and puts out the items they drop.
But he has got one problem that there are not enough sheeps, so either he have to wait a long time or he uses spawn eggs. But he wants a complete automatic machine, so please add the sheep spawner again.

### CODE REVIEW

**Comment by BlockMen** [comment]
Have you checked it? It might be outdated code from rewriting mod.

**Comment by LNJplus** [comment]
Yes the part of the spawner is commented.

**Comment by BlockMen** [comment]
> Yes the part of the spawner is commented.
See my commit.

Yeah, obviously. My question was aiming on a test/check weather that commented code is "up-to-date" with current API.

I checked it by myself now, it seems to be correct. But please remove the light values for the spawner, i guess its ok if this spawner will spawn them always. (Also the current values allows this anyway).

**Comment by BlockMen** [comment]
9b0a03ada51c42a1c8d30ea48c2ed35864286219

**Pull request closed without merging**
